runtime: go

# This sample incurs costs to run on the App Engine flexible environment. 
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_mb: 30
  limits:
  memory: 800Mi
  ephemeral-storage: 1Gi